-- MySQL Script generated by MySQL Workbench
-- 02/18/15 15:39:24
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `it111_exercise` DEFAULT CHARACTER SET latin1 ;

USE `it111_exercise` ;

-- -----------------------------------------------------
-- Table `it111_exercise`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise`.`city` (
  `city_id` INT(11) NOT NULL AUTO_INCREMENT,
  `city_code` VARCHAR(32) NULL DEFAULT NULL,
  `city_description` VARCHAR(32) NULL DEFAULT NULL,
  PRIMARY KEY (`city_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `it111_exercise`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise`.`province` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province_code` VARCHAR(32) NULL DEFAULT NULL,
  `province_description` VARCHAR(32) NULL DEFAULT NULL,
  `city_city_id` INT(11) NOT NULL,
  PRIMARY KEY (`province_id`),
  INDEX `fk_province_city1_idx` (`city_city_id` ASC),
  CONSTRAINT `fk_province_city1`
    FOREIGN KEY (`city_city_id`)
    REFERENCES `it111_exercise`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `it111_exercise`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `it111_exercise`.`region` (
  `region_id` INT(11) NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(32) NULL DEFAULT NULL,
  `region_description` VARCHAR(32) NULL DEFAULT NULL,
  `province_province_id` INT NOT NULL,
  PRIMARY KEY (`region_id`),
  INDEX `fk_region_province_idx` (`province_province_id` ASC),
  CONSTRAINT `fk_region_province`
    FOREIGN KEY (`province_province_id`)
    REFERENCES `it111_exercise`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
