-- MySQL Script generated by MySQL Workbench
-- 03/06/15 23:18:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jfk
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jfk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jfk` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `jfk` ;

-- -----------------------------------------------------
-- Table `jfk`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk`.`donation` (
  `donationNumber` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `cardType` VARCHAR(45) NOT NULL,
  `cardNumber` VARCHAR(45) NOT NULL,
  `cardHoldersName` TEXT(45) NOT NULL,
  `expirationDate` DATE NOT NULL,
  `issuingBank` TEXT(45) NULL,
  PRIMARY KEY (`donationNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk`.`country` (
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk`.`migration` (
  `version` VARCHAR(180) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `jfk`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `cus_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `birthdate` DATE NOT NULL,
  `contactNumber` INT(11) NOT NULL,
  `address` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `status` SMALLINT(6) NOT NULL DEFAULT '10',
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
