-- MySQL Script generated by MySQL Workbench
-- 02/26/15 22:29:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema JFK
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JFK
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JFK` ;
USE `JFK` ;

-- -----------------------------------------------------
-- Table `JFK`.`Registration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JFK`.`Registration` (
  `reg_id` INT NOT NULL AUTO_INCREMENT,
  `cus_name` CHAR(50) NULL,
  `birthdate` DATE NULL,
  `contactNumber` VARCHAR(50) NULL,
  `email` VARCHAR(45) NULL,
  `uname` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`reg_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JFK`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JFK`.`Users` (
  `cus_id` INT NOT NULL AUTO_INCREMENT,
  `cus_name` CHAR(50) NULL,
  `birthdate` DATE NULL,
  `contactNumber` VARCHAR(50) NULL,
  `email` VARCHAR(45) NULL,
  `uname` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `Registration_reg_id` INT NOT NULL,
  PRIMARY KEY (`cus_id`, `Registration_reg_id`),
  INDEX `fk_Users_Registration1_idx` (`Registration_reg_id` ASC),
  CONSTRAINT `fk_Users_Registration1`
    FOREIGN KEY (`Registration_reg_id`)
    REFERENCES `JFK`.`Registration` (`reg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JFK`.`PurchaseDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JFK`.`PurchaseDetails` (
  `puchaseNumber` INT NOT NULL,
  `cardType` VARCHAR(45) NOT NULL,
  `cardNumber` VARCHAR(45) NOT NULL,
  `cardHoldersName` VARCHAR(45) NOT NULL,
  `expirationDate` DATE NOT NULL,
  `issuingBank` TEXT NULL,
  `Users_cus_id` INT NOT NULL,
  PRIMARY KEY (`puchaseNumber`, `Users_cus_id`),
  INDEX `fk_PurchaseDetails_Users1_idx` (`Users_cus_id` ASC),
  CONSTRAINT `fk_PurchaseDetails_Users1`
    FOREIGN KEY (`Users_cus_id`)
    REFERENCES `JFK`.`Users` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JFK`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JFK`.`Products` (
  `stockNumber` INT NOT NULL,
  `itemType` TEXT NOT NULL,
  `itemName` TEXT NOT NULL,
  `price` INT NOT NULL,
  `size` VARCHAR(50) NULL,
  `color` VARCHAR(50) NULL,
  `PurchaseDetails_puchaseNumber` INT NOT NULL,
  PRIMARY KEY (`stockNumber`, `PurchaseDetails_puchaseNumber`),
  INDEX `fk_Products_PurchaseDetails1_idx` (`PurchaseDetails_puchaseNumber` ASC),
  CONSTRAINT `fk_Products_PurchaseDetails1`
    FOREIGN KEY (`PurchaseDetails_puchaseNumber`)
    REFERENCES `JFK`.`PurchaseDetails` (`puchaseNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JFK`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JFK`.`Event` (
  `eventNumber` INT NOT NULL,
  `eventName` VARCHAR(45) NULL,
  `eventDescription` VARCHAR(500) NULL,
  `eventDate` DATE NULL,
  `sponsorEmail` VARCHAR(45) NULL,
  `Users_cus_id` INT NOT NULL,
  PRIMARY KEY (`eventNumber`, `Users_cus_id`),
  INDEX `fk_Event_Users1_idx` (`Users_cus_id` ASC),
  CONSTRAINT `fk_Event_Users1`
    FOREIGN KEY (`Users_cus_id`)
    REFERENCES `JFK`.`Users` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JFK`.`Donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JFK`.`Donation` (
  `donationNumber` INT NOT NULL,
  `amount` INT NOT NULL,
  `cardType` VARCHAR(45) NOT NULL,
  `cardNumber` VARCHAR(45) NOT NULL,
  `cardHoldersName` TEXT NOT NULL,
  `expirationDate` DATE NOT NULL,
  `issuingBank` TEXT NULL,
  `Users_cus_id` INT NOT NULL,
  PRIMARY KEY (`donationNumber`, `Users_cus_id`),
  INDEX `fk_Donation_Users_idx` (`Users_cus_id` ASC),
  CONSTRAINT `fk_Donation_Users`
    FOREIGN KEY (`Users_cus_id`)
    REFERENCES `JFK`.`Users` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
