-- MySQL Script generated by MySQL Workbench
-- 03/07/15 15:48:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema jfk_scds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jfk_scds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jfk_scds` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `jfk_scds` ;

-- -----------------------------------------------------
-- Table `jfk_scds`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `status` SMALLINT(6) NOT NULL,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `birthdate` DATE NULL,
  `address` VARCHAR(150) NULL,
  `contact_Number` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`donation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `card_num` VARCHAR(45) NOT NULL,
  `expiry_date` DATE NOT NULL,
  `ccv` VARCHAR(45) NOT NULL,
  `first_name` TEXT NOT NULL,
  `middle_name` TEXT NULL,
  `last_name` TEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_donation_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_donation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jfk_scds`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`purchase_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`purchase_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `card_num` VARCHAR(45) NOT NULL,
  `expiry_date` DATE NOT NULL,
  `ccv` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `middle_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_purchase_details_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_purchase_details_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jfk_scds`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country_name` VARCHAR(45) NULL,
  `purchase_details_id` INT NOT NULL,
  `purchase_details_user_id` INT NOT NULL,
  `donation_id` INT NOT NULL,
  PRIMARY KEY (`id`, `purchase_details_id`, `purchase_details_user_id`, `donation_id`),
  INDEX `fk_country_purchase_details1_idx` (`purchase_details_id` ASC, `purchase_details_user_id` ASC),
  INDEX `fk_country_donation1_idx` (`donation_id` ASC),
  CONSTRAINT `fk_country_purchase_details1`
    FOREIGN KEY (`purchase_details_id` , `purchase_details_user_id`)
    REFERENCES `jfk_scds`.`purchase_details` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_country_donation1`
    FOREIGN KEY (`donation_id`)
    REFERENCES `jfk_scds`.`donation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `staff_first_name` TEXT NULL,
  `staff_last_name` TEXT NULL,
  `staff_position` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(45) NULL,
  `event_description` VARCHAR(500) NULL,
  `event_date` DATE NULL,
  `sponsor_email` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `admin_id`),
  INDEX `fk_event_user1_idx` (`user_id` ASC),
  INDEX `fk_event_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_event_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jfk_scds`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `jfk_scds`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item_type` VARCHAR(45) NULL,
  `item_name` VARCHAR(45) NULL,
  `price` DECIMAL(2) NULL,
  `size` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `purchase_details_id` INT NOT NULL,
  `purchase_details_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `purchase_details_id`, `purchase_details_user_id`),
  INDEX `fk_products_purchase_details1_idx` (`purchase_details_id` ASC, `purchase_details_user_id` ASC),
  CONSTRAINT `fk_products_purchase_details1`
    FOREIGN KEY (`purchase_details_id` , `purchase_details_user_id`)
    REFERENCES `jfk_scds`.`purchase_details` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jfk_scds`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`phone` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone_type` VARCHAR(45) NULL,
  `donation_id` INT NOT NULL,
  `purchase_details_id` INT NOT NULL,
  `purchase_details_user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `donation_id`, `purchase_details_id`, `purchase_details_user_id`),
  INDEX `fk_phone_donation1_idx` (`donation_id` ASC),
  INDEX `fk_phone_purchase_details1_idx` (`purchase_details_id` ASC, `purchase_details_user_id` ASC),
  CONSTRAINT `fk_phone_donation1`
    FOREIGN KEY (`donation_id`)
    REFERENCES `jfk_scds`.`donation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phone_purchase_details1`
    FOREIGN KEY (`purchase_details_id` , `purchase_details_user_id`)
    REFERENCES `jfk_scds`.`purchase_details` (`id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
