-- MySQL Script generated by MySQL Workbench
-- 04/17/15 18:47:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jfk_scds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jfk_scds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jfk_scds` DEFAULT CHARACTER SET latin1 ;
USE `jfk_scds` ;

-- -----------------------------------------------------
-- Table `jfk_scds`.`emailv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`emailv` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `attachment` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
