-- MySQL Script generated by MySQL Workbench
-- 04/17/15 14:19:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jfk_scds
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jfk_scds
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jfk_scds` DEFAULT CHARACTER SET latin1 ;
USE `jfk_scds` ;

-- -----------------------------------------------------
-- Table `jfk_scds`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`events` (
  `eventID` INT(11) NOT NULL AUTO_INCREMENT,
  `eventName` VARCHAR(255) NOT NULL,
  `eventDesc` VARCHAR(255) NOT NULL,
  `eventLocation` VARCHAR(255) NOT NULL,
  `eventDate` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`eventID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `jfk_scds`.`uploadpicture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jfk_scds`.`uploadpicture` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `events_eventID` INT(11) NOT NULL,
  `picture` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `events_eventID`),
  INDEX `fk_uploadpicture_events_idx` (`events_eventID` ASC),
  CONSTRAINT `fk_uploadpicture_events`
    FOREIGN KEY (`events_eventID`)
    REFERENCES `jfk_scds`.`events` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
